### ISSUE TITLE
Octave compatible?

### ISSUE THREAD

**Issue by stefano2734** [augucarv/FEM-acoustics#1]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info.
if unknown, untested with octave, info about  this also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by augucarv** [comment]
Unknown/untested. If you happen to use/test it, please cite the paper, will you? Thanks!

**Comment by stefano2734** [comment]
You are the expert of your software.

Here some infos about octave in 2022 for fast check.
https://wiki.octave.org/Differences_between_Octave_and_Matlab
https://wiki.octave.org/Release_History
https://octave.org/NEWS-7.html

you can write in your readme.
Untested with octave, but good chance or so.
Or tested with octave 7.2.
